/* Generated by           cobc 3.1.2.0 */
/* Generated from         c:\desenv\COBOL\fopag\FOLHAPAGAMENTO1.cbl */
/* Generated at           dez 04 2022 11:39:46 */
/* GnuCOBOL build date    Aug 31 2022 20:58:34 */
/* GnuCOBOL package date  Dec 23 2020 12:04:58 UTC */
/* Compile command        c:\gc312vbi\bin\cobc -x -std=ibm -Wall -I$(workspaceFolder} -IC:\desenv\COBOL\fopag\CopyBooks -IC:\desenv\COBOL\fopag\CopyBooks\Public -tFOLHAPAGAMENTO1.LST -v -g -Xref -ftsymbols c:\desenv\COBOL\fopag\FOLHAPAGAMENTO1.cbl */

#include <stdio.h>
#include <string.h>
#define  COB_KEYWORD_INLINE __inline
#include <libcob.h>

#define  COB_SOURCE_FILE		"c:\\desenv\\COBOL\\fopag\\FOLHAPAGAMENTO1.cbl"
#define  COB_PACKAGE_VERSION		"3.1.2"
#define  COB_PATCH_LEVEL		0
#define  COB_MODULE_FORMATTED_DATE	"dez 04 2022 11:39:46"
#define  COB_MODULE_DATE		20221204
#define  COB_MODULE_TIME		113946

/* Global variables */
#include "FOLHAPAGAMENTO1.c.h"

/* Function prototypes */

static int		FOLHAPAGAMENTO1 ();
static int		FOLHAPAGAMENTO1_ (const int);
static void		FOLHAPAGAMENTO1_module_init (cob_module *module);

/* Main function */
int
main (int argc, char **argv)
{
  cob_init (argc, argv);
  cob_stop_run (FOLHAPAGAMENTO1 ());
}

/* Functions */

/* PROGRAM-ID 'FOLHAPAGAMENTO1' */

/* ENTRY 'FOLHAPAGAMENTO1' */

static int
FOLHAPAGAMENTO1 ()
{
  return FOLHAPAGAMENTO1_ (0);
}

static int
FOLHAPAGAMENTO1_ (const int entry)
{
  /* Program local variables */
  #include "FOLHAPAGAMENTO1.c.l.h"

  /* Start of function code */

  /* CANCEL callback */
  if (unlikely(entry < 0)) {
  	if (entry == -10)
  		goto P_dump;
  	if (entry == -20)
  		goto P_clear_decimal;
  	goto P_cancel;
  }

  /* Check initialized, check module allocated, */
  /* set global pointer, */
  /* push module stack, save call parameter count */
  if (cob_module_global_enter (&module, &cob_glob_ptr, 0, entry, 0))
  	return -1;

  /* Set address of module parameter list */
  module->cob_procedure_params = cob_procedure_params;

  /* Set frame stack pointer */
  frame_ptr = frame_stack;
  frame_ptr->perform_through = 0;
  frame_ptr->return_address_ptr = &&P_cgerror;
  frame_overflow = frame_ptr + 255 - 1;

  /* Initialize rest of program */
  if (unlikely(initialized == 0)) {
  	goto P_initialize;
  }
  P_ret_initialize:

  /* Increment module active */
  module->module_active++;

  /* Entry dispatch */
  goto l_2;

  /* PROCEDURE DIVISION */

  /* Line: 108       : Entry     FOLHAPAGAMENTO1         : c:\desenv\COBOL\fopag\FOLHAPAGAMENTO1.cbl */
  l_2:;
#line 108 "c:\\desenv\\COBOL\\fopag\\FOLHAPAGAMENTO1.cbl"
  ENTRY_FOLHAPAGAMENTO1:;
#line 100 "FOLHAPAGAMENTO1.c"
#line 110 "c:\\desenv\\COBOL\\fopag\\FOLHAPAGAMENTO1.cbl"
  SECTION_MAIN_20SECTION:;
#line 103 "FOLHAPAGAMENTO1.c"

  /* Line: 110       : Paragraph 000000-ROTINA-PRINCIPAL : c:\desenv\COBOL\fopag\FOLHAPAGAMENTO1.cbl */
#line 110 "c:\\desenv\\COBOL\\fopag\\FOLHAPAGAMENTO1.cbl"
  cob_nop ();
#line 108 "FOLHAPAGAMENTO1.c"

  /* Line: 111       : PERFORM            : c:\desenv\COBOL\fopag\FOLHAPAGAMENTO1.cbl */
  module->module_stmt = 0x0010006F;
#line 111 "c:\\desenv\\COBOL\\fopag\\FOLHAPAGAMENTO1.cbl"
  cob_trace_stmt (st_1);
#line 114 "FOLHAPAGAMENTO1.c"
  /* PERFORM 100000-INICIO */
  frame_ptr++;
  if (unlikely(frame_ptr == frame_overflow))
  	cob_fatal_error (COB_FERROR_STACK);
  frame_ptr->perform_through = 5;
  frame_ptr->return_address_ptr = &&l_13;
  goto l_5;
  l_13:
  frame_ptr--;

  /* Line: 113       : PERFORM            : c:\desenv\COBOL\fopag\FOLHAPAGAMENTO1.cbl */
  module->module_stmt = 0x00100071;
#line 113 "c:\\desenv\\COBOL\\fopag\\FOLHAPAGAMENTO1.cbl"
  cob_trace_stmt (st_1);
#line 129 "FOLHAPAGAMENTO1.c"
  for (;;)
  {
    if (((int)(int)(*(b_114) - 83) == 0))
      break;
    /* PERFORM 200000-PROCESSA */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
    	cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 7;
    frame_ptr->return_address_ptr = &&l_14;
    goto l_7;
    l_14:
    frame_ptr--;
  }

  /* Line: 116       : PERFORM            : c:\desenv\COBOL\fopag\FOLHAPAGAMENTO1.cbl */
  module->module_stmt = 0x00100074;
#line 116 "c:\\desenv\\COBOL\\fopag\\FOLHAPAGAMENTO1.cbl"
  cob_trace_stmt (st_1);
#line 149 "FOLHAPAGAMENTO1.c"
  /* PERFORM 300000-FINALIZA */
  frame_ptr++;
  if (unlikely(frame_ptr == frame_overflow))
  	cob_fatal_error (COB_FERROR_STACK);
  frame_ptr->perform_through = 9;
  frame_ptr->return_address_ptr = &&l_15;
  goto l_9;
  l_15:
  frame_ptr--;

  /* Line: 118       : GOBACK             : c:\desenv\COBOL\fopag\FOLHAPAGAMENTO1.cbl */
  module->module_stmt = 0x00100076;
#line 118 "c:\\desenv\\COBOL\\fopag\\FOLHAPAGAMENTO1.cbl"
  cob_trace_stmt (st_2);
#line 164 "FOLHAPAGAMENTO1.c"
  goto exit_program;

  /* Line: 120       : Section   100000-INICIO           : c:\desenv\COBOL\fopag\FOLHAPAGAMENTO1.cbl */
  l_5:;
#line 120 "c:\\desenv\\COBOL\\fopag\\FOLHAPAGAMENTO1.cbl"
  SECTION_100000__INICIO:;
#line 171 "FOLHAPAGAMENTO1.c"
#line 120 "c:\\desenv\\COBOL\\fopag\\FOLHAPAGAMENTO1.cbl"
  cob_nop ();
#line 174 "FOLHAPAGAMENTO1.c"

  /* Line: 122       : DISPLAY            : c:\desenv\COBOL\fopag\FOLHAPAGAMENTO1.cbl */
  module->module_stmt = 0x0010007A;
#line 122 "c:\\desenv\\COBOL\\fopag\\FOLHAPAGAMENTO1.cbl"
  cob_trace_stmt (st_3);
#line 180 "FOLHAPAGAMENTO1.c"
  cob_display (0, 1, 2, &c_1, &f_113);

  /* Line: 123       : ACCEPT             : c:\desenv\COBOL\fopag\FOLHAPAGAMENTO1.cbl */
  module->module_stmt = 0x0010007B;
#line 123 "c:\\desenv\\COBOL\\fopag\\FOLHAPAGAMENTO1.cbl"
  cob_trace_stmt (st_4);
#line 187 "FOLHAPAGAMENTO1.c"
  cob_accept_date_yyyymmdd (&f_116);

  /* Line: 124       : ACCEPT             : c:\desenv\COBOL\fopag\FOLHAPAGAMENTO1.cbl */
  module->module_stmt = 0x0010007C;
#line 124 "c:\\desenv\\COBOL\\fopag\\FOLHAPAGAMENTO1.cbl"
  cob_trace_stmt (st_4);
#line 194 "FOLHAPAGAMENTO1.c"
  cob_accept_time (&f_121);

  /* Line: 126       : MOVE               : c:\desenv\COBOL\fopag\FOLHAPAGAMENTO1.cbl */
  module->module_stmt = 0x0010007E;
#line 126 "c:\\desenv\\COBOL\\fopag\\FOLHAPAGAMENTO1.cbl"
  cob_trace_stmt (st_5);
#line 201 "FOLHAPAGAMENTO1.c"
  memcpy (b_110, "01/01/0001", 10);

  /* Line: 127       : MOVE               : c:\desenv\COBOL\fopag\FOLHAPAGAMENTO1.cbl */
  module->module_stmt = 0x0010007F;
#line 127 "c:\\desenv\\COBOL\\fopag\\FOLHAPAGAMENTO1.cbl"
  cob_trace_stmt (st_5);
#line 208 "FOLHAPAGAMENTO1.c"
  memcpy (b_110 + 160, "00:00:00  ", 10);

  /* Line: 128       : MOVE               : c:\desenv\COBOL\fopag\FOLHAPAGAMENTO1.cbl */
  module->module_stmt = 0x00100080;
#line 128 "c:\\desenv\\COBOL\\fopag\\FOLHAPAGAMENTO1.cbl"
  cob_trace_stmt (st_5);
#line 215 "FOLHAPAGAMENTO1.c"
  cob_move_ibm (b_110, b_116 + 6, 2);

  /* Line: 129       : MOVE               : c:\desenv\COBOL\fopag\FOLHAPAGAMENTO1.cbl */
  module->module_stmt = 0x00100081;
#line 129 "c:\\desenv\\COBOL\\fopag\\FOLHAPAGAMENTO1.cbl"
  cob_trace_stmt (st_5);
#line 222 "FOLHAPAGAMENTO1.c"
  cob_move_ibm (b_110 + 3, b_116 + 4, 2);

  /* Line: 130       : MOVE               : c:\desenv\COBOL\fopag\FOLHAPAGAMENTO1.cbl */
  module->module_stmt = 0x00100082;
#line 130 "c:\\desenv\\COBOL\\fopag\\FOLHAPAGAMENTO1.cbl"
  cob_trace_stmt (st_5);
#line 229 "FOLHAPAGAMENTO1.c"
  cob_move_ibm (b_110 + 6, b_116, 4);

  /* Line: 131       : MOVE               : c:\desenv\COBOL\fopag\FOLHAPAGAMENTO1.cbl */
  module->module_stmt = 0x00100083;
#line 131 "c:\\desenv\\COBOL\\fopag\\FOLHAPAGAMENTO1.cbl"
  cob_trace_stmt (st_5);
#line 236 "FOLHAPAGAMENTO1.c"
  cob_move_ibm (b_110 + 160, b_121, 2);

  /* Line: 132       : MOVE               : c:\desenv\COBOL\fopag\FOLHAPAGAMENTO1.cbl */
  module->module_stmt = 0x00100084;
#line 132 "c:\\desenv\\COBOL\\fopag\\FOLHAPAGAMENTO1.cbl"
  cob_trace_stmt (st_5);
#line 243 "FOLHAPAGAMENTO1.c"
  cob_move_ibm (b_110 + 163, b_121 + 2, 2);

  /* Line: 133       : MOVE               : c:\desenv\COBOL\fopag\FOLHAPAGAMENTO1.cbl */
  module->module_stmt = 0x00100085;
#line 133 "c:\\desenv\\COBOL\\fopag\\FOLHAPAGAMENTO1.cbl"
  cob_trace_stmt (st_5);
#line 250 "FOLHAPAGAMENTO1.c"
  cob_move_ibm (b_110 + 166, b_121 + 4, 2);

  /* Line: 135       : OPEN               : c:\desenv\COBOL\fopag\FOLHAPAGAMENTO1.cbl */
  module->module_stmt = 0x00100087;
#line 135 "c:\\desenv\\COBOL\\fopag\\FOLHAPAGAMENTO1.cbl"
  cob_trace_stmt (st_6);
#line 257 "FOLHAPAGAMENTO1.c"
  cob_open (h_APONTAMENTOS, 1, 0, NULL);
  cob_open (h_RELATORIOFOLHA, 2, 0, NULL);
  cob_open (h_RELATORIOREJ, 2, 0, NULL);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    /* PERFORM Default Error Handler */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
    	cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 1;
    frame_ptr->return_address_ptr = &&l_16;
    goto l_1;
    l_16:
    frame_ptr--;
  }
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    /* PERFORM Default Error Handler */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
    	cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 1;
    frame_ptr->return_address_ptr = &&l_17;
    goto l_1;
    l_17:
    frame_ptr--;
  }
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    /* PERFORM Default Error Handler */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
    	cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 1;
    frame_ptr->return_address_ptr = &&l_18;
    goto l_1;
    l_18:
    frame_ptr--;
  }

  /* Line: 140       : PERFORM            : c:\desenv\COBOL\fopag\FOLHAPAGAMENTO1.cbl */
  module->module_stmt = 0x0010008C;
#line 140 "c:\\desenv\\COBOL\\fopag\\FOLHAPAGAMENTO1.cbl"
  cob_trace_stmt (st_1);
#line 302 "FOLHAPAGAMENTO1.c"
  /* PERFORM 500000-READ-APONTAMENTOS */
  frame_ptr++;
  if (unlikely(frame_ptr == frame_overflow))
  	cob_fatal_error (COB_FERROR_STACK);
  frame_ptr->perform_through = 11;
  frame_ptr->return_address_ptr = &&l_19;
  goto l_11;
  l_19:
  frame_ptr--;

  /* Implicit PERFORM return */
  for (temp_index = frame_ptr; temp_index->perform_through; temp_index--) {
    if (temp_index->perform_through == 5) {
      frame_ptr = temp_index;
      goto *frame_ptr->return_address_ptr;
    }
  }

  /* Line: 143       : Section   200000-PROCESSA         : c:\desenv\COBOL\fopag\FOLHAPAGAMENTO1.cbl */
  l_7:;
#line 143 "c:\\desenv\\COBOL\\fopag\\FOLHAPAGAMENTO1.cbl"
  SECTION_200000__PROCESSA:;
#line 325 "FOLHAPAGAMENTO1.c"
#line 143 "c:\\desenv\\COBOL\\fopag\\FOLHAPAGAMENTO1.cbl"
  cob_nop ();
#line 328 "FOLHAPAGAMENTO1.c"

  /* Line: 147       : DISPLAY            : c:\desenv\COBOL\fopag\FOLHAPAGAMENTO1.cbl */
  module->module_stmt = 0x00100093;
#line 147 "c:\\desenv\\COBOL\\fopag\\FOLHAPAGAMENTO1.cbl"
  cob_trace_stmt (st_3);
#line 334 "FOLHAPAGAMENTO1.c"
  cob_display (0, 1, 1, &c_2);

  /* Line: 152       : DISPLAY            : c:\desenv\COBOL\fopag\FOLHAPAGAMENTO1.cbl */
  module->module_stmt = 0x00100098;
#line 152 "c:\\desenv\\COBOL\\fopag\\FOLHAPAGAMENTO1.cbl"
  cob_trace_stmt (st_3);
#line 341 "FOLHAPAGAMENTO1.c"
  cob_display (0, 1, 2, &c_3, &f_9);

  /* Line: 163       : PERFORM            : c:\desenv\COBOL\fopag\FOLHAPAGAMENTO1.cbl */
  module->module_stmt = 0x001000A3;
#line 163 "c:\\desenv\\COBOL\\fopag\\FOLHAPAGAMENTO1.cbl"
  cob_trace_stmt (st_1);
#line 348 "FOLHAPAGAMENTO1.c"
  /* PERFORM 500000-READ-APONTAMENTOS */
  frame_ptr++;
  if (unlikely(frame_ptr == frame_overflow))
  	cob_fatal_error (COB_FERROR_STACK);
  frame_ptr->perform_through = 11;
  frame_ptr->return_address_ptr = &&l_20;
  goto l_11;
  l_20:
  frame_ptr--;

  /* Implicit PERFORM return */
  for (temp_index = frame_ptr; temp_index->perform_through; temp_index--) {
    if (temp_index->perform_through == 7) {
      frame_ptr = temp_index;
      goto *frame_ptr->return_address_ptr;
    }
  }

  /* Line: 166       : Section   300000-FINALIZA         : c:\desenv\COBOL\fopag\FOLHAPAGAMENTO1.cbl */
  l_9:;
#line 166 "c:\\desenv\\COBOL\\fopag\\FOLHAPAGAMENTO1.cbl"
  SECTION_300000__FINALIZA:;
#line 371 "FOLHAPAGAMENTO1.c"
#line 166 "c:\\desenv\\COBOL\\fopag\\FOLHAPAGAMENTO1.cbl"
  cob_nop ();
#line 374 "FOLHAPAGAMENTO1.c"

  /* Line: 168       : DISPLAY            : c:\desenv\COBOL\fopag\FOLHAPAGAMENTO1.cbl */
  module->module_stmt = 0x001000A8;
#line 168 "c:\\desenv\\COBOL\\fopag\\FOLHAPAGAMENTO1.cbl"
  cob_trace_stmt (st_3);
#line 380 "FOLHAPAGAMENTO1.c"
  cob_display (0, 1, 1, &c_4);

  /* Line: 171       : CLOSE              : c:\desenv\COBOL\fopag\FOLHAPAGAMENTO1.cbl */
  module->module_stmt = 0x001000AB;
#line 171 "c:\\desenv\\COBOL\\fopag\\FOLHAPAGAMENTO1.cbl"
  cob_trace_stmt (st_7);
#line 387 "FOLHAPAGAMENTO1.c"
  cob_close (h_APONTAMENTOS, NULL, 0, 0);
  cob_close (h_RELATORIOFOLHA, NULL, 0, 0);
  cob_close (h_RELATORIOREJ, NULL, 0, 0);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    /* PERFORM Default Error Handler */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
    	cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 1;
    frame_ptr->return_address_ptr = &&l_21;
    goto l_1;
    l_21:
    frame_ptr--;
  }
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    /* PERFORM Default Error Handler */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
    	cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 1;
    frame_ptr->return_address_ptr = &&l_22;
    goto l_1;
    l_22:
    frame_ptr--;
  }
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    /* PERFORM Default Error Handler */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
    	cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 1;
    frame_ptr->return_address_ptr = &&l_23;
    goto l_1;
    l_23:
    frame_ptr--;
  }

  /* Implicit PERFORM return */
  for (temp_index = frame_ptr; temp_index->perform_through; temp_index--) {
    if (temp_index->perform_through == 9) {
      frame_ptr = temp_index;
      goto *frame_ptr->return_address_ptr;
    }
  }

  /* Line: 174       : Section   500000-READ-APONTAMENTOS: c:\desenv\COBOL\fopag\FOLHAPAGAMENTO1.cbl */
  l_11:;
#line 174 "c:\\desenv\\COBOL\\fopag\\FOLHAPAGAMENTO1.cbl"
  SECTION_500000__READ__APONTAMENTOS:;
#line 440 "FOLHAPAGAMENTO1.c"
#line 174 "c:\\desenv\\COBOL\\fopag\\FOLHAPAGAMENTO1.cbl"
  cob_nop ();
#line 443 "FOLHAPAGAMENTO1.c"

  /* Line: 176       : READ               : c:\desenv\COBOL\fopag\FOLHAPAGAMENTO1.cbl */
  module->module_stmt = 0x001000B0;
#line 176 "c:\\desenv\\COBOL\\fopag\\FOLHAPAGAMENTO1.cbl"
  cob_trace_stmt (st_8);
#line 449 "FOLHAPAGAMENTO1.c"
  cob_read_next (h_APONTAMENTOS, NULL, 1);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    if (cob_glob_ptr->cob_exception_code == 0x0501)
    {

      /* Line: 178       : MOVE               : c:\desenv\COBOL\fopag\FOLHAPAGAMENTO1.cbl */
      module->module_stmt = 0x001000B2;
#line 178 "c:\\desenv\\COBOL\\fopag\\FOLHAPAGAMENTO1.cbl"
      cob_trace_stmt (st_5);
#line 460 "FOLHAPAGAMENTO1.c"
      *(b_114) = 83;
    }
    else
    {
      /* PERFORM Default Error Handler */
      frame_ptr++;
      if (unlikely(frame_ptr == frame_overflow))
      	cob_fatal_error (COB_FERROR_STACK);
      frame_ptr->perform_through = 1;
      frame_ptr->return_address_ptr = &&l_24;
      goto l_1;
      l_24:
      frame_ptr--;
    }
  }
  else
  {
    cob_move_ibm (b_18, b_18, 68);

    /* Line: 181       : ADD                : c:\desenv\COBOL\fopag\FOLHAPAGAMENTO1.cbl */
    module->module_stmt = 0x001000B5;
#line 181 "c:\\desenv\\COBOL\\fopag\\FOLHAPAGAMENTO1.cbl"
    cob_trace_stmt (st_9);
#line 484 "FOLHAPAGAMENTO1.c"
    cob_add_int (&f_127, 1, 0);
  }

  /* Implicit PERFORM return */
  for (temp_index = frame_ptr; temp_index->perform_through; temp_index--) {
    if (temp_index->perform_through == 11) {
      frame_ptr = temp_index;
      goto *frame_ptr->return_address_ptr;
    }
  }

  module->module_stmt = 0x001000BA;

  /* Program exit */

  exit_program:

  /* Decrement module active count */
  if (module->module_active) {
  	module->module_active--;
  }

  /* Pop module stack */
  cob_module_leave (module);

  /* Program return */
  return b_2;


  /* Line: 0         : Paragraph Default Error Handler   : c:\desenv\COBOL\fopag\FOLHAPAGAMENTO1.cbl */
  l_1:;
#line 0 "c:\\desenv\\COBOL\\fopag\\FOLHAPAGAMENTO1.cbl"
  cob_nop ();
#line 518 "FOLHAPAGAMENTO1.c"

  if (!(cob_glob_ptr->cob_error_file->flag_select_features & COB_SELECT_FILE_STATUS))
  	cob_fatal_error (COB_FERROR_FILE);

  /* Implicit Default Error Handler return */
  for (temp_index = frame_ptr; temp_index->perform_through; temp_index--) {
    if (temp_index->perform_through == 1) {
      frame_ptr = temp_index;
      goto *frame_ptr->return_address_ptr;
    }
  }

  /* Fatal error if reached */
  cob_fatal_error (COB_FERROR_CODEGEN);

  P_cgerror:
  	cob_fatal_error (COB_FERROR_CODEGEN);


  /* Program initialization */
  P_initialize:

  cob_check_version (COB_SOURCE_FILE, COB_PACKAGE_VERSION, COB_PATCH_LEVEL);

  cob_module_path = cob_glob_ptr->cob_main_argv0;

  FOLHAPAGAMENTO1_module_init (module);

  module->crt_status = NULL;

  /* Initialize cancel callback */
  cob_set_cancel (module);

  /* Initialize WORKING-STORAGE */
  b_2 = 0;
  memcpy (b_113, "001", 3);
  *(cob_u8_ptr)(b_114) = 78;
  memset (b_116, 48, 8);
  memset (b_121, 32, 8);
  memset (b_127, 48, 9);

  /* File initialization for APONTAMENTOS */
  cob_file_malloc (&h_APONTAMENTOS, NULL, 0, 0);
  h_APONTAMENTOS->select_name = (const char *)"APONTAMENTOS";
  h_APONTAMENTOS->file_status = h_APONTAMENTOS_status;
  memset (h_APONTAMENTOS_status, '0', 2);
  h_APONTAMENTOS->assign = (cob_field *)&c_5;
  h_APONTAMENTOS->record = &f_18;
  h_APONTAMENTOS->variable_record = NULL;
  h_APONTAMENTOS->record_min = 0;
  h_APONTAMENTOS->record_max = 68;
  h_APONTAMENTOS->nkeys = 0;
  h_APONTAMENTOS->keys = NULL;
  h_APONTAMENTOS->file = NULL;
  h_APONTAMENTOS->fd = -1;
  h_APONTAMENTOS->organization = 1;
  h_APONTAMENTOS->access_mode = 1;
  h_APONTAMENTOS->lock_mode = 0;
  h_APONTAMENTOS->open_mode = 0;
  h_APONTAMENTOS->flag_optional = 0;
  h_APONTAMENTOS->flag_line_adv = 0;
  h_APONTAMENTOS->flag_select_features = 0;

  /* File initialization for RELATORIOFOLHA */
  cob_file_malloc (&h_RELATORIOFOLHA, NULL, 0, 0);
  h_RELATORIOFOLHA->select_name = (const char *)"RELATORIOFOLHA";
  h_RELATORIOFOLHA->file_status = h_RELATORIOFOLHA_status;
  memset (h_RELATORIOFOLHA_status, '0', 2);
  h_RELATORIOFOLHA->assign = (cob_field *)&c_6;
  h_RELATORIOFOLHA->record = &f_110;
  h_RELATORIOFOLHA->variable_record = NULL;
  h_RELATORIOFOLHA->record_min = 0;
  h_RELATORIOFOLHA->record_max = 769;
  h_RELATORIOFOLHA->nkeys = 0;
  h_RELATORIOFOLHA->keys = NULL;
  h_RELATORIOFOLHA->file = NULL;
  h_RELATORIOFOLHA->fd = -1;
  h_RELATORIOFOLHA->organization = 1;
  h_RELATORIOFOLHA->access_mode = 1;
  h_RELATORIOFOLHA->lock_mode = 0;
  h_RELATORIOFOLHA->open_mode = 0;
  h_RELATORIOFOLHA->flag_optional = 0;
  h_RELATORIOFOLHA->flag_line_adv = 0;
  h_RELATORIOFOLHA->flag_select_features = 0;

  /* File initialization for RELATORIOREJ */
  cob_file_malloc (&h_RELATORIOREJ, NULL, 0, 0);
  h_RELATORIOREJ->select_name = (const char *)"RELATORIOREJ";
  h_RELATORIOREJ->file_status = h_RELATORIOREJ_status;
  memset (h_RELATORIOREJ_status, '0', 2);
  h_RELATORIOREJ->assign = (cob_field *)&c_7;
  h_RELATORIOREJ->record = &f_112;
  h_RELATORIOREJ->variable_record = NULL;
  h_RELATORIOREJ->record_min = 0;
  h_RELATORIOREJ->record_max = 132;
  h_RELATORIOREJ->nkeys = 0;
  h_RELATORIOREJ->keys = NULL;
  h_RELATORIOREJ->file = NULL;
  h_RELATORIOREJ->fd = -1;
  h_RELATORIOREJ->organization = 1;
  h_RELATORIOREJ->access_mode = 1;
  h_RELATORIOREJ->lock_mode = 0;
  h_RELATORIOREJ->open_mode = 0;
  h_RELATORIOREJ->flag_optional = 0;
  h_RELATORIOREJ->flag_line_adv = 0;
  h_RELATORIOREJ->flag_select_features = 0;

  if (0 == 1) goto P_cgerror;
  initialized = 1;
  goto P_ret_initialize;

  P_dump:
    return 0;


  /* CANCEL callback handling */
  P_cancel:

  if (!initialized)
  	return 0;
  if (module && module->module_active)
  	cob_fatal_error (COB_FERROR_CANCEL);

  initialized = 0;

  P_clear_decimal:
  return 0;

}

/* End PROGRAM-ID 'FOLHAPAGAMENTO1' */

/* Initialize module structure for FOLHAPAGAMENTO1 */
static void FOLHAPAGAMENTO1_module_init (cob_module *module)
{
  module->module_name = "FOLHAPAGAMENTO1";
  module->module_formatted_date = COB_MODULE_FORMATTED_DATE;
  module->module_source = COB_SOURCE_FILE;
  module->module_entry.funcptr = (void *(*)())FOLHAPAGAMENTO1;
  module->module_cancel.funcptr = (void *(*)())FOLHAPAGAMENTO1_;
  module->module_ref_count = NULL;
  module->module_path = &cob_module_path;
  module->module_active = 0;
  module->module_date = COB_MODULE_DATE;
  module->module_time = COB_MODULE_TIME;
  module->module_type = 0;
  module->module_param_cnt = 0;
  module->ebcdic_sign = 0;
  module->decimal_point = ',';
  module->currency_symbol = '$';
  module->numeric_separator = '.';
  module->flag_filename_mapping = 1;
  module->flag_binary_truncate = 0;
  module->flag_pretty_display = 0;
  module->flag_host_sign = 1;
  module->flag_no_phys_canc = 1;
  module->flag_main = 1;
  module->flag_fold_call = 0;
  module->flag_exit_program = 0;
  module->flag_debug_trace = 0;
  module->flag_dump_ready = 0;
  module->module_stmt = 0;
  module->module_sources = st_source_files;
}

/* End functions */

