/* Generated by           cobc 3.1.2.0 */
/* Generated from         c:\desenv\COBOL\fopag\FOLHAPAGAMENTO.cbl */
/* Generated at           dez 05 2022 08:03:56 */
/* GnuCOBOL build date    Aug 31 2022 20:58:34 */
/* GnuCOBOL package date  Dec 23 2020 12:04:58 UTC */
/* Compile command        c:\gc312vbi\bin\cobc -x -std=ibm -Wall -I$(workspaceFolder} -IC:\desenv\COBOL\fopag\CopyBooks -IC:\desenv\COBOL\fopag\CopyBooks\Public -tFOLHAPAGAMENTO.LST -v -g -Xref -ftsymbols c:\desenv\COBOL\fopag\FOLHAPAGAMENTO.cbl */


/* Module path */
static const char		*cob_module_path = NULL;

/* Number of call parameters */
static int		cob_call_params = 0;

/* Attributes */

static const cob_field_attr a_1 =	{0x21,   0,   0, 0x1000, NULL};


/* Constants */
static const cob_field c_1	= {23, (cob_u8_ptr)"FOLHAPAGAMENTO - INICIO", &a_1};


/* Strings */
static const char st_1[]	= "DISPLAY";
static const char st_2[]	= "GOBACK";


/* Source file names */
static const char *st_source_files[]	= { "" 
		,"c:\\desenv\\COBOL\\fopag\\FOLHAPAGAMENTO.cbl"};
