#line 1 "c:\desenv\COBOL\fopag\FOLHAPAGAMENTO.cbl"
 IDENTIFICATION DIVISION.
 PROGRAM-ID. FOLHAPAGAMENTO.



 ENVIRONMENT DIVISION.
 CONFIGURATION SECTION.
 SOURCE-COMPUTER. IBM-390.
 OBJECT-COMPUTER. IBM-390.
 SPECIAL-NAMES.
 DECIMAL-POINT IS COMMA.

 PROCEDURE DIVISION.
 DISPLAY 'FOLHAPAGAMENTO - INICIO' 
 GOBACK.

