/* Generated by           cobc 3.1.2.0 */
/* Generated from         c:\desenv\COBOL\fopag\FOLHAPAGAMENTO.cbl */
/* Generated at           dez 05 2022 08:03:56 */
/* GnuCOBOL build date    Aug 31 2022 20:58:34 */
/* GnuCOBOL package date  Dec 23 2020 12:04:58 UTC */
/* Compile command        c:\gc312vbi\bin\cobc -x -std=ibm -Wall -I$(workspaceFolder} -IC:\desenv\COBOL\fopag\CopyBooks -IC:\desenv\COBOL\fopag\CopyBooks\Public -tFOLHAPAGAMENTO.LST -v -g -Xref -ftsymbols c:\desenv\COBOL\fopag\FOLHAPAGAMENTO.cbl */

/* Program local variables for 'FOLHAPAGAMENTO' */

/* Module initialization indicator */
static unsigned int	initialized = 0;

/* Module structure pointer */
static cob_module	*module = NULL;

/* Global variable pointer */
cob_global		*cob_glob_ptr;


/* Call parameters */
cob_field		*cob_procedure_params[1];

/* Perform frame stack */
struct cob_frame	*temp_index;
struct cob_frame	*frame_overflow;
struct cob_frame	*frame_ptr;
struct cob_frame	frame_stack[255];


/* Data storage */
static int	b_2;	/* RETURN-CODE */

/* End of local data storage */

