/* Generated by           cobc 3.1.2.0 */
/* Generated from         c:\desenv\COBOL\fopag\FOLHAPAGAMENTO1.cbl */
/* Generated at           dez 04 2022 11:39:46 */
/* GnuCOBOL build date    Aug 31 2022 20:58:34 */
/* GnuCOBOL package date  Dec 23 2020 12:04:58 UTC */
/* Compile command        c:\gc312vbi\bin\cobc -x -std=ibm -Wall -I$(workspaceFolder} -IC:\desenv\COBOL\fopag\CopyBooks -IC:\desenv\COBOL\fopag\CopyBooks\Public -tFOLHAPAGAMENTO1.LST -v -g -Xref -ftsymbols c:\desenv\COBOL\fopag\FOLHAPAGAMENTO1.cbl */


/* Module path */
static const char		*cob_module_path = NULL;

/* Number of call parameters */
static int		cob_call_params = 0;

/* Attributes */

static const cob_field_attr a_1 =	{0x21,   0,   0, 0x1000, NULL};
static const cob_field_attr a_2 =	{0x10,   3,   0, 0x0000, NULL};
static const cob_field_attr a_3 =	{0x10,   8,   0, 0x0000, NULL};
static const cob_field_attr a_4 =	{0x21,   0,   0, 0x0000, NULL};
static const cob_field_attr a_5 =	{0x10,   9,   0, 0x0000, NULL};


/* Constants */
static const cob_field c_1	= {39, (cob_u8_ptr)"000 - INICIO PROGRAMA FOLHAPAGAMENTO V.", &a_1};
static const cob_field c_2	= {14, (cob_u8_ptr)"20000-PROCESSA", &a_1};
static const cob_field c_3	= {24, (cob_u8_ptr)"NUM-MATRICULA          =", &a_1};
static const cob_field c_4	= {8, (cob_u8_ptr)"FINALIZA", &a_1};
static const cob_field c_5	= {16, (cob_u8_ptr)"APONTAMENTOS.DAT", &a_1};
static const cob_field c_6	= {18, (cob_u8_ptr)"RELATORIOFOLHA.TXT", &a_1};
static const cob_field c_7	= {16, (cob_u8_ptr)"RELATORIOREJ.TXT", &a_1};


/* Strings */
static const char st_1[]	= "PERFORM";
static const char st_2[]	= "GOBACK";
static const char st_3[]	= "DISPLAY";
static const char st_4[]	= "ACCEPT";
static const char st_5[]	= "MOVE";
static const char st_6[]	= "OPEN";
static const char st_7[]	= "CLOSE";
static const char st_8[]	= "READ";
static const char st_9[]	= "ADD";


/* Source file names */
static const char *st_source_files[]	= { "" 
		,"c:\\desenv\\COBOL\\fopag\\FOLHAPAGAMENTO1.cbl"};
